# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import sil_snomed_core.fields
import django.contrib.postgres.fields


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationReferenceSetDenormalizedView',
            fields=[
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('row_id', models.UUIDField(editable=False)),
                ('effective_time', models.DateField(editable=False)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('module_id', models.BigIntegerField(editable=False)),
                ('module_name', models.TextField(editable=False)),
                ('refset_id', models.BigIntegerField(editable=False)),
                ('refset_name', models.TextField(editable=False)),
                ('referenced_component_id', models.BigIntegerField(editable=False)),
                ('referenced_component_name', models.TextField(null=True, editable=False, blank=True)),
                ('annotation', models.TextField()),
            ],
            options={
                'verbose_name': 'annotation_refset_view',
                'db_table': 'annotation_reference_set_expanded_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnnotationReferenceSetDynamicSnapshot',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('annotation', models.TextField()),
            ],
            options={
                'verbose_name': 'annotation_refset_snapshot',
                'db_table': 'snomed_annotation_reference_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssociationReferenceSetDenormalizedView',
            fields=[
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('row_id', models.UUIDField(editable=False)),
                ('effective_time', models.DateField(editable=False)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('module_id', models.BigIntegerField(editable=False)),
                ('module_name', models.TextField(editable=False)),
                ('refset_id', models.BigIntegerField(editable=False)),
                ('refset_name', models.TextField(editable=False)),
                ('referenced_component_id', models.BigIntegerField(editable=False)),
                ('referenced_component_name', models.TextField(null=True, editable=False, blank=True)),
                ('target_component_id', models.BigIntegerField()),
                ('target_component_name', models.TextField(null=True, editable=False, blank=True)),
            ],
            options={
                'verbose_name': 'association_refset_view',
                'db_table': 'association_reference_set_expanded_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssociationReferenceSetDynamicSnapshot',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('target_component_id', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'association_refset_snapshot',
                'db_table': 'snomed_association_reference_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeValueReferenceSetDenormalizedView',
            fields=[
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('row_id', models.UUIDField(editable=False)),
                ('effective_time', models.DateField(editable=False)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('module_id', models.BigIntegerField(editable=False)),
                ('module_name', models.TextField(editable=False)),
                ('refset_id', models.BigIntegerField(editable=False)),
                ('refset_name', models.TextField(editable=False)),
                ('referenced_component_id', models.BigIntegerField(editable=False)),
                ('referenced_component_name', models.TextField(null=True, editable=False, blank=True)),
                ('value_id', models.BigIntegerField(editable=False)),
                ('value_name', models.TextField(null=True, editable=False, blank=True)),
            ],
            options={
                'verbose_name': 'attrib_value_refset_view',
                'db_table': 'attribute_value_reference_set_expanded_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeValueReferenceSetDynamicSnapshot',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('value_id', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'attribute_value_refset_snapshot',
                'db_table': 'snomed_attribute_value_reference_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComplexMapReferenceSetDenormalizedView',
            fields=[
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('row_id', models.UUIDField(editable=False)),
                ('effective_time', models.DateField(editable=False)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('module_id', models.BigIntegerField(editable=False)),
                ('module_name', models.TextField(editable=False)),
                ('refset_id', models.BigIntegerField(editable=False)),
                ('refset_name', models.TextField(editable=False)),
                ('referenced_component_id', models.BigIntegerField(editable=False)),
                ('referenced_component_name', models.TextField(null=True, editable=False, blank=True)),
                ('map_group', models.IntegerField(editable=False)),
                ('map_priority', models.IntegerField(editable=False)),
                ('map_rule', models.TextField(editable=False)),
                ('map_advice', models.TextField(editable=False)),
                ('map_target', models.CharField(max_length=256, editable=False)),
                ('correlation_id', models.BigIntegerField(editable=False)),
                ('correlation_name', models.TextField(null=True, editable=False, blank=True)),
                ('map_block', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'verbose_name': 'complex_map_refset_view',
                'db_table': 'complex_map_reference_set_expanded_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComplexMapReferenceSetDynamicSnapshot',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('map_group', models.IntegerField()),
                ('map_priority', models.IntegerField()),
                ('map_rule', models.TextField()),
                ('map_advice', models.TextField()),
                ('map_target', models.CharField(max_length=256)),
                ('correlation_id', models.BigIntegerField()),
                ('map_block', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'verbose_name': 'complex_map_refset_snapshot',
                'db_table': 'snomed_complex_map_reference_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConceptDenormalizedView',
            fields=[
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('concept_id', models.BigIntegerField(editable=False)),
                ('effective_time', models.DateField(editable=False)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('is_primitive', models.BooleanField(default=False, editable=False)),
                ('module_id', models.BigIntegerField(editable=False)),
                ('module_name', models.TextField(editable=False)),
                ('definition_status_id', models.BigIntegerField(editable=False)),
                ('definition_status_name', models.TextField(editable=False)),
                ('fully_specified_name', sil_snomed_core.fields.DenormalizedDescriptionField(editable=False)),
                ('preferred_term', sil_snomed_core.fields.DenormalizedDescriptionField(editable=False)),
                ('definition', sil_snomed_core.fields.DenormalizedDescriptionField(null=True, editable=False, blank=True)),
                ('descriptions', sil_snomed_core.fields.DenormalizedDescriptionArrayField(editable=False)),
                ('preferred_terms', sil_snomed_core.fields.DenormalizedDescriptionArrayField(editable=False)),
                ('synonyms', sil_snomed_core.fields.DenormalizedDescriptionArrayField(editable=False)),
                ('is_a_parents', sil_snomed_core.fields.ExpandedRelationshipField(editable=False)),
                ('is_a_children', sil_snomed_core.fields.ExpandedRelationshipField(editable=False)),
                ('is_a_direct_parents', sil_snomed_core.fields.ExpandedRelationshipField(editable=False)),
                ('is_a_direct_children', sil_snomed_core.fields.ExpandedRelationshipField(editable=False)),
                ('part_of_parents', sil_snomed_core.fields.ExpandedRelationshipField(editable=False)),
                ('part_of_children', sil_snomed_core.fields.ExpandedRelationshipField(editable=False)),
                ('part_of_direct_parents', sil_snomed_core.fields.ExpandedRelationshipField(editable=False)),
                ('part_of_direct_children', sil_snomed_core.fields.ExpandedRelationshipField(editable=False)),
                ('other_parents', sil_snomed_core.fields.ExpandedRelationshipField(editable=False)),
                ('other_children', sil_snomed_core.fields.ExpandedRelationshipField(editable=False)),
                ('other_direct_parents', sil_snomed_core.fields.ExpandedRelationshipField(editable=False)),
                ('other_direct_children', sil_snomed_core.fields.ExpandedRelationshipField(editable=False)),
            ],
            options={
                'db_table': 'concept_expanded_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConceptDynamicSnapshot',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('component_id', models.BigIntegerField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('definition_status_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'snomed_concept',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DescriptionDenormalizedView',
            fields=[
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('component_id', models.BigIntegerField(editable=False)),
                ('effective_time', models.DateField(editable=False)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('language_code', models.CharField(max_length=2, editable=False)),
                ('term', models.TextField(editable=False)),
                ('module_id', models.BigIntegerField(editable=False)),
                ('module_name', models.TextField(editable=False)),
                ('concept_id', models.BigIntegerField(editable=False)),
                ('concept_name', models.TextField(editable=False)),
                ('type_id', models.BigIntegerField(editable=False)),
                ('type_name', models.TextField(editable=False)),
                ('case_significance_id', models.BigIntegerField(editable=False)),
                ('case_significance_name', models.TextField(editable=False)),
            ],
            options={
                'db_table': 'description_expanded_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DescriptionDynamicSnapshot',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('component_id', models.BigIntegerField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('concept_id', models.BigIntegerField()),
                ('language_code', models.CharField(default=b'en', max_length=2)),
                ('type_id', models.BigIntegerField()),
                ('case_significance_id', models.BigIntegerField()),
                ('term', models.TextField()),
            ],
            options={
                'db_table': 'snomed_description',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DescriptionFormatReferenceSetDenormalizedView',
            fields=[
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('row_id', models.UUIDField(editable=False)),
                ('effective_time', models.DateField(editable=False)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('module_id', models.BigIntegerField(editable=False)),
                ('module_name', models.TextField(editable=False)),
                ('refset_id', models.BigIntegerField(editable=False)),
                ('refset_name', models.TextField(editable=False)),
                ('referenced_component_id', models.BigIntegerField(editable=False)),
                ('referenced_component_name', models.TextField(null=True, editable=False, blank=True)),
                ('description_format_id', models.BigIntegerField()),
                ('description_format_name', models.TextField(null=True, editable=False, blank=True)),
                ('description_length', models.IntegerField()),
            ],
            options={
                'verbose_name': 'desc_format_refset_view',
                'db_table': 'description_format_reference_set_expanded_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DescriptionFormatReferenceSetDynamicSnapshot',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('description_format_id', models.BigIntegerField()),
                ('description_length', models.IntegerField()),
            ],
            options={
                'verbose_name': 'description_format_refset_snapshot',
                'db_table': 'snomed_description_format_reference_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtendedMapReferenceSetDenormalizedView',
            fields=[
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('row_id', models.UUIDField(editable=False)),
                ('effective_time', models.DateField(editable=False)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('module_id', models.BigIntegerField(editable=False)),
                ('module_name', models.TextField(editable=False)),
                ('refset_id', models.BigIntegerField(editable=False)),
                ('refset_name', models.TextField(editable=False)),
                ('referenced_component_id', models.BigIntegerField(editable=False)),
                ('referenced_component_name', models.TextField(null=True, editable=False, blank=True)),
                ('map_group', models.IntegerField(editable=False)),
                ('map_priority', models.IntegerField(editable=False)),
                ('map_rule', models.TextField(editable=False)),
                ('map_advice', models.TextField(editable=False)),
                ('map_target', models.CharField(max_length=256, editable=False)),
                ('correlation_id', models.BigIntegerField(editable=False)),
                ('correlation_name', models.TextField(null=True, editable=False, blank=True)),
                ('map_category_id', models.BigIntegerField()),
                ('map_category_name', models.TextField(null=True, editable=False, blank=True)),
            ],
            options={
                'verbose_name': 'extended_map_refset_view',
                'db_table': 'extended_map_reference_set_expanded_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ExtendedMapReferenceSetDynamicSnapshot',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('map_group', models.IntegerField()),
                ('map_priority', models.IntegerField()),
                ('map_rule', models.TextField()),
                ('map_advice', models.TextField()),
                ('map_target', models.CharField(max_length=256)),
                ('correlation_id', models.BigIntegerField()),
                ('map_category_id', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'extended_map_refset_snapshot',
                'db_table': 'snomed_extended_map_reference_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageReferenceSetDenormalizedView',
            fields=[
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('row_id', models.UUIDField(editable=False)),
                ('effective_time', models.DateField(editable=False)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('module_id', models.BigIntegerField(editable=False)),
                ('module_name', models.TextField(editable=False)),
                ('refset_id', models.BigIntegerField(editable=False)),
                ('refset_name', models.TextField(editable=False)),
                ('referenced_component_id', models.BigIntegerField(editable=False)),
                ('referenced_component_name', models.TextField(null=True, editable=False, blank=True)),
                ('acceptability_id', models.BigIntegerField()),
                ('acceptability_name', models.TextField(null=True, editable=False, blank=True)),
            ],
            options={
                'verbose_name': 'lang_refset_view',
                'db_table': 'language_reference_set_expanded_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageReferenceSetDynamicSnapshot',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('acceptability_id', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'language_map_refset_snapshot',
                'db_table': 'snomed_language_reference_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuleDependencyReferenceSetDenormalizedView',
            fields=[
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('row_id', models.UUIDField(editable=False)),
                ('effective_time', models.DateField(editable=False)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('module_id', models.BigIntegerField(editable=False)),
                ('module_name', models.TextField(editable=False)),
                ('refset_id', models.BigIntegerField(editable=False)),
                ('refset_name', models.TextField(editable=False)),
                ('referenced_component_id', models.BigIntegerField(editable=False)),
                ('referenced_component_name', models.TextField(null=True, editable=False, blank=True)),
                ('source_effective_time', models.DateField()),
                ('target_effective_time', models.DateField()),
            ],
            options={
                'verbose_name': 'module_dep_refset_view',
                'db_table': 'module_dependency_reference_set_expanded_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ModuleDependencyReferenceSetDynamicSnapshot',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('source_effective_time', models.DateField()),
                ('target_effective_time', models.DateField()),
            ],
            options={
                'verbose_name': 'mod_dep_refset_snapshot',
                'db_table': 'snomed_module_dependency_reference_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderedReferenceSetDenormalizedView',
            fields=[
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('row_id', models.UUIDField(editable=False)),
                ('effective_time', models.DateField(editable=False)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('module_id', models.BigIntegerField(editable=False)),
                ('module_name', models.TextField(editable=False)),
                ('refset_id', models.BigIntegerField(editable=False)),
                ('refset_name', models.TextField(editable=False)),
                ('referenced_component_id', models.BigIntegerField(editable=False)),
                ('referenced_component_name', models.TextField(null=True, editable=False, blank=True)),
                ('order', models.PositiveSmallIntegerField(editable=False)),
                ('linked_to_id', models.BigIntegerField(editable=False)),
                ('linked_to_name', models.TextField(null=True, editable=False, blank=True)),
            ],
            options={
                'db_table': 'ordered_reference_set_expanded_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderedReferenceSetDynamicSnapshot',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('linked_to_id', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'ordered_refset_snapshot',
                'db_table': 'snomed_ordered_reference_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuerySpecificationReferenceSetDenormalizedView',
            fields=[
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('row_id', models.UUIDField(editable=False)),
                ('effective_time', models.DateField(editable=False)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('module_id', models.BigIntegerField(editable=False)),
                ('module_name', models.TextField(editable=False)),
                ('refset_id', models.BigIntegerField(editable=False)),
                ('refset_name', models.TextField(editable=False)),
                ('referenced_component_id', models.BigIntegerField(editable=False)),
                ('referenced_component_name', models.TextField(null=True, editable=False, blank=True)),
                ('query', models.TextField()),
            ],
            options={
                'verbose_name': 'query_spec_refset_view',
                'db_table': 'query_specification_reference_set_expanded_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuerySpecificationReferenceSetDynamicSnapshot',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('query', models.TextField()),
            ],
            options={
                'verbose_name': 'query_spec_refset_snapshot',
                'db_table': 'snomed_query_specification_reference_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenceSetDescriptorReferenceSetDenormalizedView',
            fields=[
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('row_id', models.UUIDField(editable=False)),
                ('effective_time', models.DateField(editable=False)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('module_id', models.BigIntegerField(editable=False)),
                ('module_name', models.TextField(editable=False)),
                ('refset_id', models.BigIntegerField(editable=False)),
                ('refset_name', models.TextField(editable=False)),
                ('referenced_component_id', models.BigIntegerField(editable=False)),
                ('referenced_component_name', models.TextField(null=True, editable=False, blank=True)),
                ('attribute_description_id', models.BigIntegerField()),
                ('attribute_description_name', models.TextField(null=True, editable=False, blank=True)),
                ('attribute_type_id', models.BigIntegerField()),
                ('attribute_type_name', models.TextField(null=True, editable=False, blank=True)),
                ('attribute_order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'refset_descriptor_refset_view',
                'db_table': 'reference_set_descriptor_reference_set_expanded_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenceSetDescriptorReferenceSetDynamicSnapshot',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('attribute_description_id', models.BigIntegerField()),
                ('attribute_type_id', models.BigIntegerField()),
                ('attribute_order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'refset_descriptor_refset_snapshot',
                'db_table': 'snomed_reference_set_descriptor_reference_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelationshipDenormalizedView',
            fields=[
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('component_id', models.BigIntegerField(editable=False)),
                ('effective_time', models.DateField(editable=False)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('relationship_group', models.SmallIntegerField(null=True, editable=False, blank=True)),
                ('module_id', models.BigIntegerField(editable=False)),
                ('module_name', models.TextField(editable=False)),
                ('source_id', models.BigIntegerField(editable=False)),
                ('source_name', models.TextField(editable=False)),
                ('destination_id', models.BigIntegerField(editable=False)),
                ('destination_name', models.TextField(editable=False)),
                ('type_id', models.BigIntegerField(editable=False)),
                ('type_name', models.TextField(editable=False)),
                ('characteristic_type_id', models.BigIntegerField(editable=False)),
                ('characteristic_type_name', models.TextField(editable=False)),
                ('modifier_id', models.BigIntegerField(editable=False)),
                ('modifier_name', models.TextField(editable=False)),
            ],
            options={
                'db_table': 'relationship_expanded_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelationshipDynamicSnapshot',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('component_id', models.BigIntegerField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('source_id', models.BigIntegerField()),
                ('destination_id', models.BigIntegerField()),
                ('relationship_group', models.PositiveSmallIntegerField(default=0)),
                ('type_id', models.BigIntegerField()),
                ('characteristic_type_id', models.BigIntegerField()),
                ('modifier_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'snomed_relationship',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SearchContentView',
            fields=[
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('concept_id', models.BigIntegerField(editable=False)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('is_primitive', models.BooleanField(default=False, editable=False)),
                ('module_id', models.BigIntegerField(editable=False)),
                ('module_name', models.TextField(editable=False)),
                ('fully_specified_name', models.TextField(editable=False)),
                ('preferred_term', models.TextField(editable=False)),
                ('descriptions', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), editable=False, size=None)),
                ('is_a_parent_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), editable=False, size=None)),
                ('is_a_children_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), editable=False, size=None)),
                ('refset_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), editable=False, size=None)),
            ],
            options={
                'db_table': 'search_content_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleMapReferenceSetDenormalizedView',
            fields=[
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('row_id', models.UUIDField(editable=False)),
                ('effective_time', models.DateField(editable=False)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('module_id', models.BigIntegerField(editable=False)),
                ('module_name', models.TextField(editable=False)),
                ('refset_id', models.BigIntegerField(editable=False)),
                ('refset_name', models.TextField(editable=False)),
                ('referenced_component_id', models.BigIntegerField(editable=False)),
                ('referenced_component_name', models.TextField(null=True, editable=False, blank=True)),
                ('map_target', models.CharField(max_length=256, editable=False)),
            ],
            options={
                'verbose_name': 'simple_map_refset_view',
                'db_table': 'simple_map_reference_set_expanded_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleMapReferenceSetDynamicSnapshot',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('map_target', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'simple_map_refset_snapshot',
                'db_table': 'snomed_simple_map_reference_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleReferenceSetDenormalizedView',
            fields=[
                ('id', models.IntegerField(serialize=False, editable=False, primary_key=True)),
                ('row_id', models.UUIDField(editable=False)),
                ('effective_time', models.DateField(editable=False)),
                ('active', models.BooleanField(default=True, editable=False)),
                ('module_id', models.BigIntegerField(editable=False)),
                ('module_name', models.TextField(editable=False)),
                ('refset_id', models.BigIntegerField(editable=False)),
                ('refset_name', models.TextField(editable=False)),
                ('referenced_component_id', models.BigIntegerField(editable=False)),
                ('referenced_component_name', models.TextField(null=True, editable=False, blank=True)),
            ],
            options={
                'db_table': 'simple_reference_set_expanded_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SimpleReferenceSetDynamicSnapshot',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
            ],
            options={
                'verbose_name': 'simple_refset_snapshot',
                'db_table': 'snomed_simple_reference_set',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubsumptionView',
            fields=[
                ('concept_id', models.BigIntegerField(serialize=False, editable=False, primary_key=True)),
                ('is_a_direct_parents', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), editable=False, size=None)),
                ('is_a_parents', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), editable=False, size=None)),
                ('is_a_direct_children', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), editable=False, size=None)),
                ('is_a_children', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), editable=False, size=None)),
                ('part_of_direct_parents', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), editable=False, size=None)),
                ('part_of_parents', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), editable=False, size=None)),
                ('part_of_direct_children', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), editable=False, size=None)),
                ('part_of_children', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), editable=False, size=None)),
                ('other_direct_parents', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), editable=False, size=None)),
                ('other_parents', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), editable=False, size=None)),
                ('other_direct_children', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), editable=False, size=None)),
                ('other_children', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), editable=False, size=None)),
            ],
            options={
                'db_table': 'snomed_subsumption',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnnotationReferenceSetFull',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('annotation', models.TextField()),
            ],
            options={
                'db_table': 'snomed_annotation_reference_set_full',
            },
        ),
        migrations.CreateModel(
            name='AssociationReferenceSetFull',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('target_component_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'snomed_association_reference_set_full',
            },
        ),
        migrations.CreateModel(
            name='AttributeValueReferenceSetFull',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('value_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'snomed_attribute_value_reference_set_full',
            },
        ),
        migrations.CreateModel(
            name='ComplexMapReferenceSetFull',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('map_group', models.IntegerField()),
                ('map_priority', models.IntegerField()),
                ('map_rule', models.TextField()),
                ('map_advice', models.TextField()),
                ('map_target', models.CharField(max_length=256)),
                ('correlation_id', models.BigIntegerField()),
                ('map_block', models.IntegerField(null=True, blank=True)),
            ],
            options={
                'db_table': 'snomed_complex_map_reference_set_full',
            },
        ),
        migrations.CreateModel(
            name='ConceptFull',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('component_id', models.BigIntegerField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('definition_status_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'snomed_concept_full',
            },
        ),
        migrations.CreateModel(
            name='DescriptionFormatReferenceSetFull',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('description_format_id', models.BigIntegerField()),
                ('description_length', models.IntegerField()),
            ],
            options={
                'db_table': 'snomed_description_format_reference_set_full',
                'verbose_name': 'description_format_refset_full',
            },
        ),
        migrations.CreateModel(
            name='DescriptionFull',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('component_id', models.BigIntegerField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('concept_id', models.BigIntegerField()),
                ('language_code', models.CharField(default=b'en', max_length=2)),
                ('type_id', models.BigIntegerField()),
                ('case_significance_id', models.BigIntegerField()),
                ('term', models.TextField()),
            ],
            options={
                'db_table': 'snomed_description_full',
            },
        ),
        migrations.CreateModel(
            name='ExtendedMapReferenceSetFull',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('map_group', models.IntegerField()),
                ('map_priority', models.IntegerField()),
                ('map_rule', models.TextField()),
                ('map_advice', models.TextField()),
                ('map_target', models.CharField(max_length=256)),
                ('correlation_id', models.BigIntegerField()),
                ('map_category_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'snomed_extended_map_reference_set_full',
            },
        ),
        migrations.CreateModel(
            name='LanguageReferenceSetFull',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('acceptability_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'snomed_language_reference_set_full',
            },
        ),
        migrations.CreateModel(
            name='ModuleDependencyReferenceSetFull',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('source_effective_time', models.DateField()),
                ('target_effective_time', models.DateField()),
            ],
            options={
                'db_table': 'snomed_module_dependency_reference_set_full',
            },
        ),
        migrations.CreateModel(
            name='OrderedReferenceSetFull',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField()),
                ('linked_to_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'snomed_ordered_reference_set_full',
            },
        ),
        migrations.CreateModel(
            name='QuerySpecificationReferenceSetFull',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('query', models.TextField()),
            ],
            options={
                'db_table': 'snomed_query_specification_reference_set_full',
            },
        ),
        migrations.CreateModel(
            name='ReferenceSetDescriptorReferenceSetFull',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('attribute_description_id', models.BigIntegerField()),
                ('attribute_type_id', models.BigIntegerField()),
                ('attribute_order', models.IntegerField()),
            ],
            options={
                'db_table': 'snomed_reference_set_descriptor_reference_set_full',
                'verbose_name': 'refset_descriptor_refset_full',
            },
        ),
        migrations.CreateModel(
            name='RelationshipFull',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('component_id', models.BigIntegerField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('source_id', models.BigIntegerField()),
                ('destination_id', models.BigIntegerField()),
                ('relationship_group', models.PositiveSmallIntegerField(default=0)),
                ('type_id', models.BigIntegerField()),
                ('characteristic_type_id', models.BigIntegerField()),
                ('modifier_id', models.BigIntegerField()),
            ],
            options={
                'db_table': 'snomed_relationship_full',
            },
        ),
        migrations.CreateModel(
            name='ServerNamespaceIdentifier',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('extension_item_type', models.CharField(max_length=14, choices=[(b'DESCRIPTION', b'DESCRIPTION'), (b'CONCEPT', b'CONCEPT'), (b'RELATIONSHIP', b'RELATIONSHIP')])),
                ('extension_item_identifier', models.BigIntegerField()),
            ],
            options={
                'db_table': 'server_namespace_identifier',
            },
        ),
        migrations.CreateModel(
            name='SimpleMapReferenceSetFull',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
                ('map_target', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'snomed_simple_map_reference_set_full',
            },
        ),
        migrations.CreateModel(
            name='SimpleReferenceSetFull',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('row_id', models.UUIDField()),
                ('effective_time', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('module_id', models.BigIntegerField()),
                ('refset_id', models.BigIntegerField()),
                ('referenced_component_id', models.BigIntegerField()),
                ('pending_rebuild', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 'snomed_simple_reference_set_full',
            },
        ),
        migrations.AlterUniqueTogether(
            name='servernamespaceidentifier',
            unique_together=set([('extension_item_identifier', 'extension_item_type')]),
        ),
    ]
