"""Remove target_component_id and replace with annotation

Revision ID: e18723243afd
Revises: 5c81d646a2a0
Create Date: 2016-05-31 12:09:26.027654

"""

# revision identifiers, used by Alembic.
revision = 'e18723243afd'
down_revision = '5c81d646a2a0'

from alembic import op
import sqlalchemy as sa
import sil_snomed_server



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curr_annotationrefset_f', sa.Column('annotation', sa.Text(), nullable=True))
    op.drop_column('curr_annotationrefset_f', 'target_component_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curr_annotationrefset_f', sa.Column('target_component_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('curr_annotationrefset_f', 'annotation')
    ### end Alembic commands ###
