---
- hosts: all
  vars:
    deploy_user: deploy
    deploy_group: deploy
    deploy_user_home: /home/{{deploy_user}}
  name: Deploy the Buildserver owned and maintained by the Slade360 SNOMED CT Clinical Terminologies Project

  tags: [ "snomedct_buildserver" ]
  pre_tasks:
    - name: create deploy user
      user: name="{{deploy_user}}" groups=sudo state=present
      sudo: yes

  roles:

    - {
      role: snomedct_buildserver,
      become: yes,
      become_method: sudo,
      become_user: "{{deploy_user}}",
      tags: ["snomedct_buildserver"]
      }
