# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-18 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='language_code',
            field=models.TextField(default='en'),
            preserve_default=False,
        ),
    ]
