# -*- coding: utf-8 -*-
# Generated by Django 1.10b1 on 2016-07-18 08:26
from __future__ import unicode_literals

import os

from django.db import migrations


SQL = open(os.path.dirname(__file__) + '/sql/final_load.sql').read()


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_description_language_code'),
    ]

    operations = [
        migrations.RunSQL(SQL)
    ]
