---
install_dir: "/opt/snomedct_buildserver"
venv_dir: "{{install_dir}}/env"
env_file: "snomedct_buildserver.env.sh"
db_host: localhost
db_port: 5432
database_url: "postgres://{{db_user}}:{{db_pass}}@{{db_host}}:{{db_port}}/{{db_name}}"
